languageCode = "en"
languageName = "English"
weight = 1
title = "Dev Mahmoud"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Laravel + Vue.js: The perfect pair for full-stack development. Fast, scalable, secure, and easy to learn."
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Mahmoud Adel"
  image = "img/mahmoud_adel.jpg"
  headline = "Full Stack Developer"
  bio = "Full Stack Developer"
  links = [
      { email = "mailto:zwebcourses@gmail.com" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
      { dev = "https://bit.ly/devmahmoud" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
      { facebook = "https://bit.ly/fb-laravelspa" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
      { github = "https://bit.ly/gb-laravelspa" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
      { hashnode = "https://bit.ly/hn-laravelspa" },
      { instagram = "https://bit.ly/in-laravelspa" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
      { linkedin = "https://bit.ly/linked-devmahmoud" },
  #    { mastodon = "https://bit.ly/mastodon-zwc" },
      { medium = "https://bit.ly/meduim-mahmoud" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
      { pinterest = "https://bit.ly/pt-laravelspa" },
  #   { reddit = "https://bit.ly/redt-zwc" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
      { stack-overflow = "https://bit.ly/sof-mahmoud" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
      { telegram = "https://t.me/+Orn4XkfoT0diN2I0" },
      { tiktok = "https://bit.ly/tk-laravelspa" },
     { tumblr = "https://laravelspa.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
      { twitter = "https://bit.ly/tw-laravelspa" },
      { whatsapp = "https://chat.whatsapp.com/KxYv6AFXYA2H1pD6VZn9hW" },
      { youtube = "https://bit.ly/yt-laravelspa" },
  #   { ko-fi = "https://ko-fi.com/username" },
  ]
