# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Portfolio"
  pageRef = "portfolio"
  weight = 20

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 30

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 40

[[main]]
  name = "Series"
  pageRef = "series"
  weight = 50

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
   name = "Privacy Policy"
   pageRef = "privacy-policy"
   weight = 10

[[footer]]
   name = "Terms and Conditions"
   pageRef = "terms-and-conditions"
   weight = 20

[[footer]]
   name = "Subscribe"
   pageRef = "subscribe"
   weight = 30

[[footer]]
   name = "Contact Us"
   pageRef = "contact-us"
   weight = 40

[[footer]]
   name = "About Us"
   pageRef = "about-us"
   weight = 50

 